### ISSUE TITLE
POST http://localhost:3000/api/users 404 (Not Found)

### ISSUE THREAD

**Issue by aadityarajkumawat** [bradtraversy/devconnector_2.0#137]
Even after applying proxy in client/package.json, the client is making request to port 3000, instead of 5000, I have been copying the exact code from the course, where are the things going wrong

please help

**Comment by bushblade** [comment]
Hi @aadityarajkumawat.
Yes that's what should be happening.
In the browser the requests will be going to port 3000.
Then the dev server from CRA/Webpack proxy that request for us to port 5000
We do this so we don't break the browsers Same Origin Policy in development.
If for some reason your server is not responding then you will see an error like.
Unable to proxy request from 3000 to 5000, because the dev server isn't getting a response or is getting a bad response from the server.
Are you a student of Brad's?
If so please post in the course Q&A and one of us will help you out.
I'll close as an issue here as this is not an issue with the current repository code.
