### ISSUE TITLE
Regarding github section in the profile 

### ISSUE THREAD

**Issue by abdullahmujahidali** [bradtraversy/devconnector_2.0#165]
I am getting this error and I have tried everything can I get some help
![image](https://user-images.githubusercontent.com/48271080/93057955-23831600-f688-11ea-9671-d3d949abbb58.png)

Below is the code 
`import React, { useEffect } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { getGithubRepos } from '../../actions/profile';

const ProfileGithub = ({ username, getGithubRepos, repos }) => {
  useEffect(() => {
    getGithubRepos(username);
  }, [getGithubRepos],username);

  return (
    <div className="profile-github">
      <h2 className="text-primary my-1">Github Repos</h2>
      {repos.map(repo => (
        <div key={repo.id} className="repo bg-white p-1 my-1">
          <div>
            <h4>
              <a href={repo.html_url} target="_blank" rel="noopener noreferrer">
                {repo.name}
              </a>
            </h4>
            <p>{repo.description}</p>
          </div>
          <div>
            <ul>
              <li className="badge badge-primary">
                Stars: {repo.stargazers_count}
              </li>
              <li className="badge badge-dark">
                Watchers: {repo.watchers_count}
              </li>
              <li className="badge badge-light">Forks: {repo.forks_count}</li>
            </ul>
          </div>
        </div>
      ))}
    </div>
  );
};

ProfileGithub.propTypes = {
  getGithubRepos: PropTypes.func.isRequired,
  repos: PropTypes.array.isRequired,
  username: PropTypes.string.isRequired
};

const mapStateToProps = state => ({
  repos: state.profile.repos
});

export default connect(mapStateToProps, { getGithubRepos })(ProfileGithub);`

**Comment by bushblade** [comment]
Hi @abdullahmujahidali 
What's the issue you're having it's not clear from your post?
Is it the 404 response in your console from trying to fetch the repos?
In which case that would imply that the user has no GitHub account, or there is some issue with your back end code in fetching the repos.
I can't really tell what you're showing us here or what your issue is really but must likely your issue is not where you think it is.
Test your end points in Postman, I suspect there is something going wrong with your back end code (if indeed I have guessed your issue is fetching the repos).
I'm also assuming this is your own code/project and not the repository code?
In which case if you're a student of Brad's then please post in the course Q&A and one of us will help you there.
If you're not a student and just need a working project then please fork and clone this repository.
As this isn't an issue with the repository code I'll close as an issue here on GitHub.

**Comment by abdullahmujahidali** [comment]
Thankyou for your reply but I checked on postman it was fetching data correctly related to repos.
