### ISSUE TITLE
Homepage is rendered even when the user is logged in on changing the url manually

### ISSUE THREAD

**Issue by ashish25-bit** [bradtraversy/devconnector_2.0#170]
When the user is logged and change the url from '/dashboard' to '/' or '/login' the homepage or login page respectively is being rendered. 

So when the user requests for '/' or '/login' or '/register' the when logged in, a pre-loader should be rendered util the user is authenticated instead of rendering the login or the signup page which is the current behaviour. 

This issue is kind of same to the one in the the route is not maintained when the page is refreshed.

**Comment by bushblade** [comment]
Hi @ashish25-bit 
Can you just confirm that this is an issue with the latest repo code please?
We get a lot of students creating issues that are actually problems with their own code/project.

**Comment by ashish25-bit** [comment]
> Hi @ashish25-bit
> Can you just confirm that this is an issue with the latest repo code please?
> We get a lot of students creating issues that are actually problems with their own code/project.

Hello @bushblade.
Yes this issue is with the lastest repo code one on the master branch.

**Comment by bushblade** [comment]
Hi again @ashish25-bit 
I'm not sure I follow what your saying is an issue here.

_When the user is logged and change the url from '/dashboard' to '/' or '/login' the homepage or login page respectively is being rendered._

In the case of a user being logged in if they visit '/' or 'login' by manipulating the url they will be redirected to '/dashboard'

_So when the user requests for '/' or '/login' or '/register' the when logged in, a pre-loader should be rendered util the user is authenticated instead of rendering the login or the signup page which is the current behaviour_
 
In the case of a user being logged in already then they are already logged in so no loading of auth state is needed, it's already happened. In the case of a user being authenticated, we show a Spinner component until authentication is complete.

Unless I'm missing your point I don't see any issue with the current repository code here.

**Comment by ashish25-bit** [comment]
![issue](https://user-images.githubusercontent.com/55174290/95685809-d6a74680-0c17-11eb-967b-136aef40f5a1.gif)

Hey @bushblade 
Sorry for replying late. 
As you can see in the above gif, when I am changing the url from '/dashboard' to '/' the homepage is being shown for a split second and then the authenticated user is redirected to the dashboard.

**Comment by bushblade** [comment]
Hi again @ashish25-bit 
Well yes it will, that's what's meant to happen.
In [Landing.js](https://github.com/bradtraversy/devconnector_2.0/blob/0b08fd722260fcd2cb8957c4682e941afee9e721/client/src/components/layout/Landing.js#L7) we have
```js
  if (isAuthenticated) {
    return <Redirect to='/dashboard' />;
  }
```

**Comment by bushblade** [comment]
I'll close as an issue as unless I'm mistaken you seem to be describing the desired behaviour.
