### ISSUE TITLE
unable to change html part

### ISSUE THREAD

**Issue by shakti2604535** [bradtraversy/devconnector_2.0#214]

**Comment by pascalsarr** [comment]
@bushblade a tu une idée meme moi j'ai ce meme problème @shakti2604535.

**Comment by bushblade** [comment]
@pascalsarr @shakti2604535 I have no idea what the problem is.
There is no description, no instructions to reproduce the issue, no error output, no screenshots... No info at all.
Please @shakti2604535 if you are going to create an issue, then you will have to provide a good deal more information.
I'll close as there is nothing really to go on here.
