### ISSUE TITLE
TypeError: Cannot read property 'params' of undefined

### ISSUE THREAD

**Issue by yousuf4you** [bradtraversy/devconnector_2.0#237]
```TypeError: Cannot read property 'params' of undefined``` 

error on ```./profile/Profile``` component.
![devcon1](https://user-images.githubusercontent.com/60110696/126855689-caeee26f-7148-48c5-b7a2-d59688f2ae1b.png)

![devcon2](https://user-images.githubusercontent.com/60110696/126855624-1c62995e-c61c-46e4-8e82-9e3de2858f11.png)

**Comment by thefstalphabet** [comment]
I can't get the file where this error is present.

**Comment by bushblade** [comment]
Hi @yousuf4you 
Are you using the latest code from the repository? I cannot reproduce this issue.
If you are one of Brad's students and this is your own code then please post in the course Q&A and one of us will get to you, make sure to include a link to your repository so we can see all your code.
The match object is supplied to this component as it is the child of a react-router-dom <Route /> component. So if you don't have access to the match object and you are following the course code then your issue is elsewhere higher up.

**Comment by bushblade** [comment]
Closing due to lack of information and stale issue.
