### ISSUE TITLE
Issue when deleting entry from database. This state…filter is not an option? React Reducers

### ISSUE THREAD

**Issue by kirasiris** [bradtraversy/devconnector_2.0#38]
I currently have this in my reducer as initial state:
```
const initialState = {
  posts: [],
  post: null,
  loading: true,
  error: {}
};
```
and then I have this method:
```
case DELETE_POST:
      return {
        ...state,
        posts: state.posts.filter(post => post._id !== payload),
        loading: false
      };
```
Every time I delete an entry from my database, an error is displayed stating that 'state.pages.filter is not a function'. I've been struggling with this quite some time already. Any help will be really appreciated!.

**Comment by HixOba** [comment]
@kirasiris, did you sort it out eventually?
I had same problem using .map (instead of .filter) but same prob. I traced it back to my 'form@ - in your case i would think your posts form.

I suspect an IF statement of the type:

if (post !== null && post.length === 0 && !loading) {
    return <h3>Add posts details from here</h3>
  }

Which is what i adjusted it to, and it worked. Goodluck!

**Comment by bushblade** [comment]
As this has gone a little stale, has lack of actionable information and doesn't appear to be an issue with the current repo code, I'm closing this issue.
