### ISSUE TITLE
Compiled with warnings

### ISSUE THREAD

**Issue by richyrb00** [bradtraversy/devconnector_2.0#4]
Brad,

I've ran the install on demo and hooked it up to a fresh db. so everything is clean and i get these warnings in the terminal.

Compiled with warnings.

./src/components/profile/ProfileGithub.js
Line 10:  React Hook useEffect has a missing dependency: 'username'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/components/post/Post.js
Line 14:  React Hook useEffect has a missing dependency: 'match.params.id'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/actions/post.js
Line 158:  'res' is assigned a value but never used  no-unused-vars

./src/components/post/CommentItem.js
Line 1:  'Fragment' is defined but never used  no-unused-vars

./src/components/profile-forms/EditProfile.js
Line 48:  React Hook useEffect has missing dependencies: 'profile.bio', 'profile.company', 'profile.githubusername', 'profile.location', 'profile.skills', 'profile.social', 'profile.status', and 'profile.website'. Either include them or remove the dependency array. If 'setFormData' needs the current value of 'profile.company', you can also switch to useReducer instead of useState and read 'profile.company' in the reducer  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by timoheimmel** [comment]
Yes, as richyrb00 said. Compiles with these warnings. Should they be ignored or fixed?

**Comment by richyrb00** [comment]
They can be ignored with an walnut comment but ideally anything like this should have a solution. No one likes warnings on a production build.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by richyrb00** [comment]
EsLint* comment. Lol

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by kwibus2000** [comment]
One more issue: ProfileGithub.js line 19: repo does not have an repo.-id; use key={repo.id} instead.

**Comment by Zed-M** [comment]
yeah I have the same issue, and also the developers page isn't showing for some reason

**Comment by Zed-M** [comment]
### Fixing all the compiling issues is quite simple! they are just eslint warnings,

_fixes:_

_1)./src/components/profile/ProfileGithub.js
Line 10: React Hook useEffect has a missing dependency: 'username'.  =>_ 

from   `useEffect(() => {getGithubRepos(username);}, [getGithubRepos]);`
to
  `useEffect(() => {getGithubRepos(username);}, [getGithubRepos, username]);`

**same fix for all useffect warnings just add the argument you passed to the array:** 

_2)./src/components/post/Post.js
Line 14: React Hook useEffect has a missing dependency: 'match.params.id'._
  `useEffect(() => { getPost(match.params.id);}, [getPost, match.params.id]);`

_3)./src/actions/post.js
Line 158: 'res' is assigned a value but never used no-unused-vars_

**because we are not using the res.data in the dispatch payload we are just calling the comment id**

from this `const res = await axios.delete(`/api/posts/comment/${postId}/${commentId}`);` 
to 
`await axios.delete(`/api/posts/comment/${postId}/${commentId}`);`

_4)./src/components/post/CommentItem.js
Line 1: 'Fragment' is defined but never used no-unused-vars_

**just wrap the render div with <Fragement> and close it at the end <Fragement/>**

_5)./src/components/profile-forms/EditProfile.js
Line 48: React Hook useEffect has missing dependencies: 'profile.bio', 'profile.company', 'profile.githubusername', 'profile.location', 'profile.skills', 'profile.social', 'profile.status', and 'profile.website'._

`useffect ..... }, [loading, getCurrentProfile, profile.bio, profile.company, profile.githubusername, profile.location, profile.skills, profile.social, profile.status, profile.website]);`

**Comment by yomi05** [comment]
> , profile.bio, profile.company, profile.githubusername, profile.location, profile.skills, profile.social, profile.status, profile.website

I battled with the issue five but it kept on breaking the app but this worked

  useEffect(() => {
    getCurrentProfile();
    setFormData({
      company: loading || !profile.company ? '' : profile.company,
      website: loading || !profile.website ? '' : profile.website,
      location: loading || !profile.location ? '' : profile.location,
      status: loading || !profile.status ? '' : profile.status,
      skills: loading || !profile.skills ? '' : profile.skills.join(','),
      githubusername:
        loading || !profile.githubusername ? '' : profile.githubusername,
      bio: loading || !profile.bio ? '' : profile.bio,
      twitter: loading || !profile.social ? '' : profile.social.twitter,
      facebook: loading || !profile.social ? '' : profile.social.facebook,
      linkedin: loading || !profile.social ? '' : profile.social.linkedin,
      youtube: loading || !profile.social ? '' : profile.social.youtube,
      instagram: loading || !profile.social ? '' : profile.social.instagram
    });
  }, [loading, getCurrentProfile]); // eslint-disable-line

**Comment by mygitH1** [comment]
> ### Fixing all the compiling issues is quite simple! they are just eslint warnings,
> _fixes:_
> 
> _1)./src/components/profile/ProfileGithub.js Line 10: React Hook useEffect has a missing dependency: 'username'. =>_
> 
> from `useEffect(() => {getGithubRepos(username);}, [getGithubRepos]);`
> to
> `useEffect(() => {getGithubRepos(username);}, [getGithubRepos, username]);`
> 
> **same fix for all useffect warnings just add the argument you passed to the array:**
> 
> _2)./src/components/post/Post.js Line 14: React Hook useEffect has a missing dependency: 'match.params.id'._
> `useEffect(() => { getPost(match.params.id);}, [getPost, match.params.id]);`
> 
> _3)./src/actions/post.js Line 158: 'res' is assigned a value but never used no-unused-vars_
> 
> **because we are not using the res.data in the dispatch payload we are just calling the comment id**
> 
> from this `const res = await axios.delete(`/api/posts/comment/${postId}/${commentId}`);`
> to
> `await axios.delete(`/api/posts/comment/${postId}/${commentId}`);`
> 
> _4)./src/components/post/CommentItem.js Line 1: 'Fragment' is defined but never used no-unused-vars_
> 
> **just wrap the render div with `<Fragement>` and close it at the end `<Fragement/>`**
> 
> _5)./src/components/profile-forms/EditProfile.js Line 48: React Hook useEffect has missing dependencies: 'profile.bio', 'profile.company', 'profile.githubusername', 'profile.location', 'profile.skills', 'profile.social', 'profile.status', and 'profile.website'._
> 
> `useffect ..... }, [loading, getCurrentProfile, profile.bio, profile.company, profile.githubusername, profile.location, profile.skills, profile.social, profile.status, profile.website]);`
> 
> **I also downloaded and added a spinner.gif file into the component/layout folder ( i didn't find it in the project it should be there though )**

This was very helpful Zed-M. Thank you Sir.

**Comment by bushblade** [comment]
As this has been stale for over 6 months and does not appear to be an issue with the repo code, I'm closing this issue.
