### ISSUE TITLE
Refreshing on /posts page no longer reload posts.

### ISSUE THREAD

**Issue by Lunastryke** [bradtraversy/devconnector_2.0#86]
A continuation of issue #85, after i reverted the changes made to routing in #75, pull request #83 breaks the refreshing on the /posts page as now I receive a error 401 with invalid authentication status

**Comment by bushblade** [comment]
Hi @Lunastryke I tried reproducing your error but I am unable to on the current code base ( no revert), refreshing does redirect to the dashboard but refreshing will reload the app so the whole process of authenticating a user will run again.
If you're getting the error after reverting the changes then I would say don't revert the changes.
I wasn't familiar with the early versions of this app, is the expected behaviour to reload the posts if a user is authenticated?
I think keeping the private routes private (#75) is probably a priority over refreshing/reloading posts but if this gets more attention then perhaps we can look into it.

**Comment by corey01** [comment]
I've had a go at trying to fix this,

I'm not an expert at user auth so please let me know if my solution leaves any security holes, but it seems to work..

#96

**Comment by Kade-Powell** [comment]
I gave your suggestion a go, but when i refreshed the posts page it still did not load the posts.
the post are still trying to load before the user is authenticated.

![image](https://user-images.githubusercontent.com/47295838/78693859-d4aba600-78c9-11ea-903d-ad5875e35d5c.png)

**Comment by bushblade** [comment]
Hi @Kade-Powell and @Lunastryke , would you mind cloning the [refreshroutes branch](https://github.com/bushblade/devconnector_2.0/tree/refreshroutes) in my repo and testing that out?

**Comment by Kade-Powell** [comment]
yep that works now when refreshing i get the posts, i didn't need to make any changes to my auth reducer just PrivateRoute and Routes. Is it because PrivateRoute checks for loading to be done before it checks isAuthenticated? as opposed to the old way i had it checking isAuthenticated first

**Comment by bushblade** [comment]
@Kade-Powell Thanks for checking. I'm not certain in your case as it sounds like you may have differences elsewhere between your code and the repo code? So I couldn't say for certain.
Glad it's working for you though.
